bin2c -o bishop.c bishop.png
bin2c -o bishop_bl.c bishop_bl.png
bin2c -o game_start.c game_start.png
bin2c -o game_ended1.c game_ended1.png
bin2c -o game_ended2.c game_ended2.png
bin2c -o game_ended3.c game_ended3.png
bin2c -o king.c king.png
bin2c -o king_bl.c king_bl.png
bin2c -o knight.c knight.png
bin2c -o knight_bl.c knight_bl.png
bin2c -o pawn.c pawn.png
bin2c -o pawn_bl.c pawn_bl.png
bin2c -o queen.c queen.png
bin2c -o queen_bl.c queen_bl.png
bin2c -o rook.c rook.png
bin2c -o rook_bl.c rook_bl.png
bin2c -o icon.c icon.ico